name: AreaManager
main: AreaManager\Main
version: 1.1
api: [3.0.0, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]
load: STARTUP
author: lakwsh
website: https://lakwsh.net

commands:
 area:
  usage: "/area <rm/set/srm/cp/pt>"
  permission: AreaManager

permissions:
 AreaManager:
  default: true