name: AreaManage
main: lakwsh\AreaManage\AreaManage
version: 1.0
api: [3.0.0, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]
load: STARTUP
author: lakwsh
website: https://lakwsh.net

commands:
 area:
  usage: "/area <rm/set/srm/cp/pt>"
  permission: AreaManage.area
  description: "快速建造选点"
 lw:
  usage: "/lw"
  permission: AreaManage.lw
  description: "显示所有世界"
 w:
  usage: "/w <地图名>"
  permission: AreaManage.w
  description: "传送到另一个世界"

permissions:
 AreaManage:
  default: false
  children:
   AreaManage.area:
    default: true
   AreaManage.lw:
    default: true
   AreaManage.w:
    default: true